apiVersion: v1
kind: Service
metadata:
  name: tech-test
spec:
  selector:
    app: tech-test
  ports:
    - port: 8090
      targetPort: 8090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-test
  template:
    metadata:
      labels:
        app: tech-test
    spec:
      containers:
        - name: app
          image: richardwwalter/tech-test-service
          ports:
            - containerPort: 8090
#          env:
#            - name: MONGO_URL
#              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always